### PR TITLE
PSDK-123 GoodPandas classmethod to load credentials from config file

### PR DESCRIPTION
**Pull request by hkad98**
Load credentials for GoodPandas from the config file

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by jaceksan — APPROVED** [review]

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/51/ : SUCCESS in 1m 17s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/201/ : FAILURE in 7s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/204/ : SUCCESS in 17s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR220

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/52/ : SUCCESS in 1m 14s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/202/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/205/ : SUCCESS in 16s

**Pull request merged**
