### PR TITLE
FIX: hugo build action

### PR DESCRIPTION
**Pull request by hkad98**
* added HUGO_ENV

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by mouchar** [comment]
setting HUGO_ENV to public has far more consequences than just setting `index,follow` in meta tag!

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by mouchar — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR197

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/28/ : SUCCESS in 1m 29s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/178/ : SUCCESS in 1m 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/181/ : SUCCESS in 19s

**Pull request merged**
