### PR TITLE
Removing Comment PR job

### PR DESCRIPTION
**Pull request by Mara3l**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by Mara3l** [comment]
There is currently a failing job: https://github.com/gooddata/gooddata-python-sdk/actions/runs/5645258774/job/15292021260?pr=285#step:8:1

It is a known issue, and our infra is working on a solution. In the meantime, it would be better to just comment it ou.

**Review by hkad98 — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR295

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/111/ : FAILURE in 49s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/261/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/264/ : SUCCESS in 16s

**Pull request merged**
