### PR TITLE
fix(py-sdk): Add noop AllMetricValueFilter

### PR DESCRIPTION
**Pull request by torchbear**
- required for filter description

JIRA: CQ-299

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/342/ : FAILURE in 1m 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/492/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/496/ : SUCCESS in 7s

**Pull request merged**
