### PR TITLE
TNT-939 Update fixture according to api specification

### PR DESCRIPTION
**Pull request by pbenes**
The specification of `AfmObjectIdentifierAttribute` requires type: "attribute" which is used in `PopDateMeasureDefinition`

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by hkad98** [comment]
@pcerny @jaceksan 
Please do not merge this request. GitHub did not trigger tests, and before merging, we should verify that it did not break any tests.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
Closed in favor of https://github.com/gooddata/gooddata-python-sdk/pull/124

**Pull request closed without merging**
