### PR TITLE
PSDK-95: Enable schemata parameter in ScanRequest

### PR DESCRIPTION
**Pull request by jaceksan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by hkad98** [comment]
Consider replacing create_directory with recreate_directory in every test that performs store. Now you have it only in tests related to workspace content, but it might be beneficial to have it in others.

Also, I thought that we will perform recreate in store class methods.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by jaceksan** [comment]
> Consider replacing create_directory with recreate_directory in every test that performs store. Now you have it only in tests related to workspace content, but it might be beneficial to have it in others.
> 
> Also, I thought that we will perform recreate in store class methods.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by jaceksan** [comment]
> Consider replacing create_directory with recreate_directory in every test that performs store. Now you have it only in tests related to workspace content, but it might be beneficial to have it in others.
> 
> Also, I thought that we will perform recreate in store class methods.

I updated all tests.
When I updated store methods in SDK, many tests start failing because changed vcr cassette. Leaving it for a follow-up.

**Review by hkad98 — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR150

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/136/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/136/ : FAILURE in 11s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/138/ : SUCCESS in 22s

**Pull request merged**
