### PR TITLE
PSDK-150: localization - handle missing title/description in ADM

### PR DESCRIPTION
**Pull request by jaceksan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR288

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/105/ : FAILURE in 2s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/255/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/258/ : SUCCESS in 17s

**Pull request merged**
