### PR TITLE
Add jwt token to the sdk

### PR DESCRIPTION
**Pull request by samuelsalon**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/122/ : FAILURE in 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/272/ : SUCCESS in 59s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/275/ : SUCCESS in 10s

**Pull request merged**
