### PR TITLE
PSDK-136: Add basic support for collectLabelsElements API

### PR DESCRIPTION
**Pull request by jaceksan**
Plus PSDK-144: Allow custom path to localization file
Plus PSDK-146: Localization - translate titles/descr in headers of dashboard rows

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR276

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/98/ : FAILURE in 2m 21s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/248/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/251/ : SUCCESS in 20s

**Pull request merged**
