### PR TITLE
LX-18: Support validateBy option for collectLabelElement api

### PR DESCRIPTION
**Pull request by mcermak**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by pcerny — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR514

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/297/ : FAILURE in 1m 24s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/447/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/451/ : SUCCESS in 9s

**Pull request merged**
