### PR TITLE
feature(gooddata-sdk): Add locales support for AbsoluteDateFilter

### PR DESCRIPTION
**Pull request by torchbear**
Allow locales formatting of AbsoluteDateFilter when `icu` package is installed.

JIRA: CQ-95

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Pull request merged**
