### PR TITLE
NAS-2887 update code to GD.CN 1.6

### PR DESCRIPTION
**Pull request by pcerny**
- OpenAPI clients re-generated with generator in version 5.3.1
- gooddata-sdk code updated to work with new versions of OpenAPI clients
- vcr cassette files updated
- gooddata-sdk vcr tests re-directed to AIO image

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by mira01 — CHANGES_REQUESTED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR60

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/53/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/53/ : FAILURE in 11m 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/53/ : SUCCESS in 19s

**Pull request merged**
