### PR TITLE
XSH-783 Export type for label_overrides

### PR DESCRIPTION
**Pull request by Dominik-Sauer**
to allow typechecking in clients

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by danielfojt — APPROVED** [review]

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR143

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/129/ : SUCCESS in 1m 09s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/129/ : FAILURE in 12s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/131/ : SUCCESS in 20s

**Pull request merged**
