### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by hkad98**
- .dockerignore for docs
- use wheel in tox
- use uv in tox

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by jaceksan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR583

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/335/ : FAILURE in 1m 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/485/ : SUCCESS in 57s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/489/ : SUCCESS in 6s

**Pull request merged**
