### PR TITLE
TRIVIAL: gooddata-dbt - better reporting to stdout and pipeline logs

### PR DESCRIPTION
**Pull request by jaceksan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — CHANGES_REQUESTED** [review]
Please add tabulate dependency to setup.py as well.

**Review by hkad98 — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR375

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/188/ : FAILURE in 2m 22s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/338/ : SUCCESS in 1m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/341/ : SUCCESS in 9s

**Pull request merged**
