### PR TITLE
Changing documentation links for README.md

### PR DESCRIPTION
**Pull request by Mara3l**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by hkad98 — APPROVED** [review]

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-python-sdk-fossa-scanning-zuul : SKIPPED (non-voting)
- gooddata-python-sdk-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-python-sdk-merge-compliance-check : NOT_REGISTERED

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR199

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/29/ : SUCCESS in 2m 00s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/179/ : SUCCESS in 2m 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/182/ : SUCCESS in 23s

**Pull request merged**
