### PR TITLE
CQ-223: Enhance total exec support for pivot tables

### PR DESCRIPTION
**Pull request by Tjev**
Using `sdk.table.for_insight` now creates totals and dimensions for pivot tables. This is done similarly as in gooddata-ui-sdk.

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by Tjev** [comment]
Switching to https://github.com/gooddata/gooddata-python-sdk/pull/567, due to malformed branch history.

**Pull request closed without merging**
