### PR TITLE
PSDK-133 brotli compression support

### PR DESCRIPTION
**Pull request by hkad98**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by hkad98** [comment]
I added **DO NOT MERGE** label. Let's merge it after [PR#221](https://github.com/gooddata/gooddata-python-sdk/pull/221) and [PR#220](https://github.com/gooddata/gooddata-python-sdk/pull/220) are merged.

**Review by jaceksan — APPROVED** [review]

**Review by mouchar — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR222

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/55/ : SUCCESS in 1m 18s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/205/ : SUCCESS in 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/208/ : SUCCESS in 13s

**Pull request merged**
