### PR TITLE
refactor(gooddata-sdk) - Switch up function definitions ordering

### PR DESCRIPTION
**Pull request by Tjev**
JIRA: CQ-89

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR587

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul/334/ : FAILURE in 1m 20s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/484/ : SUCCESS in 1m 24s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/488/ : SUCCESS in 7s

**Pull request merged**
