### PR TITLE
NAS-3893 add permission service

### PR DESCRIPTION
**Pull request by hkad98**
Added:
* permission service
* validation for permission names
* test support

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-python-sdk-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-python-sdk-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/104/ : FAILURE in 24s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- gooddata-python-sdk-sonarqube-scan-zuul-gate : SKIPPED
- gooddata-python-sdk-fossa-scanning-zuul-el7 : SKIPPED (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/105/ : FAILURE in 19s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-python-sdk-gate-PR112

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-sonarqube-scan-zuul-gate/104/ : SUCCESS in 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-fossa-scanning-zuul-el7/104/ : SUCCESS in 2m 18s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-python-sdk-merge-compliance-check/106/ : SUCCESS in 20s

**Pull request merged**
